version: '2'
services:
    gestao-app:
        image: gestao
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gestao-mysql:3306/gestao?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=gestao-elasticsearch:9300
        ports:
            - 8080:8080
    gestao-mysql:
        extends:
            file: mysql.yml
            service: gestao-mysql
    gestao-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gestao-elasticsearch
